name: akuru_drop
description: Akuru Drop - A Dhivehi Thaana match-3 puzzle game.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.22.0
  flame_audio: ^2.10.0
  audioplayers: ^6.0.0
  go_router: ^17.0.0
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_mobile_ads: ^5.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  vibration: ^2.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/background/
    - assets/images/icons/
    - assets/music/
    - assets/sfx/
    - assets/levels/
    - assets/data/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: MVFaseyha
      fonts:
        - asset: assets/fonts/MVFaseyha.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#0A1628"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
